# Generated by Django 3.1.3 on 2020-11-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_city_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
